import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Logo from "./components/logo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "JIITAK Inc",
  description: "Generated by create next app",
};

export default function ResetPasswordLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div className="flex flex-col gap-0.5 min-h-screen">
        <Logo />
        {children}
      </div>
    </main>
  );
}
