export const data = [
  {
    nickname: "cfyvgbh",
    email: "random6@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "xrdtcfybhj",
    email: "random7@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "zxrdcfvgbh",
    email: "random8@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "cyfgb",
    email: "random9@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "xdcfghbj",
    email: "random10@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "kjbhvgcf",
    email: "random11@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "rdctfvghj",
    email: "rdm12@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "tcfvghj",
    email: "rdm13@gmail.com",
    year_month: "2024 04",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "lkjhg",
    email: "rdm14@gmail.com",
    year_month: "2024 01",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "cfyvgbh",
    email: "random6@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "xrdtcfybhj",
    email: "random7@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "zxrdcfvgbh",
    email: "random8@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "cyfgb",
    email: "random9@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "xdcfghbj",
    email: "random10@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "kjbhvgcf",
    email: "random11@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "rdctfvghj",
    email: "rdm12@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "tcfvghj",
    email: "rdm13@gmail.com",
    year_month: "2024 04",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "lkjhg",
    email: "rdm14@gmail.com",
    year_month: "2024 01",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "cfyvgbh",
    email: "random6@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "xrdtcfybhj",
    email: "random7@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "zxrdcfvgbh",
    email: "random8@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "cyfgb",
    email: "random9@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "xdcfghbj",
    email: "random10@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "kjbhvgcf",
    email: "random11@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "rdctfvghj",
    email: "rdm12@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "tcfvghj",
    email: "rdm13@gmail.com",
    year_month: "2024 04",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "lkjhg",
    email: "rdm14@gmail.com",
    year_month: "2024 01",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "cfyvgbh",
    email: "random6@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "xrdtcfybhj",
    email: "random7@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "zxrdcfvgbh",
    email: "random8@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "cyfgb",
    email: "random9@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "xdcfghbj",
    email: "random10@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "kjbhvgcf",
    email: "random11@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "rdctfvghj",
    email: "rdm12@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "tcfvghj",
    email: "rdm13@gmail.com",
    year_month: "2024 04",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "lkjhg",
    email: "rdm14@gmail.com",
    year_month: "2024 01",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "cfyvgbh",
    email: "random6@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "xrdtcfybhj",
    email: "random7@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "zxrdcfvgbh",
    email: "random8@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "cyfgb",
    email: "random9@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "xdcfghbj",
    email: "random10@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "kjbhvgcf",
    email: "random11@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "rdctfvghj",
    email: "rdm12@gmail.com",
    year_month: "2024 06",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "tcfvghj",
    email: "rdm13@gmail.com",
    year_month: "2024 04",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
  {
    nickname: "lkjhg",
    email: "rdm14@gmail.com",
    year_month: "2024 01",
    gender: "Male",
    prefecture: "NA",
    registrationDate: "2024 01 02",
  },
];
